[directories]
base = D:\ARSciLab
; base = D:\HLVR\HLVR_dev
; windows = \Packaged\Windows\HomeLabVR\Content\Paks
; android = \Saved\StagedBuilds\Android_ASTC\HomeLabVR\Content\Paks
windows = \Packaged\Windows\ARSciLab\Content\Paks
android = \Saved\StagedBuilds\Android_ASTC\ARSciLab\Content\Paks
experiment = \Saved\HLVR\JSON
; video180 = D:\HLVR\SourceFiles\180
; output = W:\HLVR_CDN
output = W:\ARSciLab_CDN
media = D:\HLVR\media
subtitles = D:\HLVR\Subtitles\converted




